workflow:
  name: '$PIPELINE_NAME'
  rules:
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/
      variables:
        PIPELINE_NAME: 'Manual pipeline to $GITLAB_ENV'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        PIPELINE_NAME: 'MR pipeline'
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
      variables:
        PIPELINE_NAME: 'Commit pipeline'

# ------------------------

variables:
  GITLAB_ENV:
    description: 'Which environment do you want to deploy to?'
    value: 'test'
    options:
      - 'demo'
      - 'rework'
      - 'stable'
      - 'staging'
      - 'test'
  SERVICE: ${SERVICE}

default:
  tags:
    - shell

stages:
  - test
  - deploy
  - update
  - e2e-test

include:
  - project: fairdata/fairdata-ci
    ref: master
    file:
      - /templates/deploy/deploy-jobs.yaml
      - /templates/test/test-jobs.yaml
      - /templates/test/etsin-qvain-tests.yaml
      - /templates/deploy/etsin-deploy-jobs.yaml

# ------------------------

etsin-qvain-tests:
  stage: test
  extends: .etsin-qvain-tests-docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

sonarqube:
  stage: test
  extends: .sonarqube-job
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

# ------------------------

deploy:
  extends: .deploy-job
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

deploy-rework:
  extends: .deploy-job
  variables:
    GITLAB_ENV: 'rework'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

deploy-feature:
  extends: .deploy-feature-job
  variables:
    GITLAB_ENV: 'staging'
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# ------------------------

update-proxy:
  extends: .update-proxy-job
  environment: test
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

update-proxy-rework:
  extends: .update-proxy-job
  environment: rework
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

update-proxy-feature:
  extends: .update-proxy-job
  environment: staging
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# ------------------------

fairdata-e2e:
  stage: e2e-test
  trigger: fairdata/fairdata-ci
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

fairdata-e2e-feature:
  stage: e2e-test
  trigger: fairdata/fairdata-ci
  variables:
    GITLAB_ENV: staging
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
