version: '3.8'
services:
    etsin-qvain-webpack:
      image: fairdata-docker.artifactory.ci.csc.fi/fairdata-etsin-qvain-webpack
      hostname: 'etsin-qvain-webpack'
      ports:
        - 8080:8080
      command: npm run dev
      volumes:
        - ./etsin_finder/:/etsin_finder/
      depends_on:
        - backend
      environment:
        - CHOKIDAR_USEPOLLING=true
        - base_url=0.0.0.0:8080
    etsin-qvain-flask:
      image: fairdata-docker.artifactory.ci.csc.fi/fairdata-etsin-qvain-flask
      hostname: 'etsin-qvain-flask'
      configs:
        - source: etsin-qvain-app-config
          target: /home/etsin-user/app_config
      volumes:
        - ./etsin_finder/:/etsin_finder/
        - ./tests/:/tests/
      environment:
        - base_url=0.0.0.0:5000
        - FLASK_ENV=development
        - PYTHONPATH=/
        - FLASK_DEBUG=1
    etsin-qvain-elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
      hostname: 'etsin-qvain-elasticsearch'
      environment:
        - base_url=0.0.0.0:9201
        - http.host=0.0.0.0
        - transport.host=0.0.0.0
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        - "discovery.type=single-node"
      volumes:
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    etsin-qvain-memcached:
      image: memcached:latest
      hostname: 'etsin-qvain-memcached'
      ports:
        - "11211:11211"
      command: ["memcached"]
    fairdata-nginx:
      image: nginx:latest
      configs:
        - source: fairdata-nginx-config
          target: /etc/nginx/nginx.conf
        - source: fairdata-ssl-certificate
          target: /etc/pki/tls/certs/ssl.crt.pem
        - source: fairdata-ssl-certificate-key
          target: /etc/pki/tls/private/ssl.key.pem
        - source: etsin-qvain-nginx-config
          target: /etc/nginx/sites-enabled/etsin-qvain
      ports:
        - 443:443
      volumes:
        - ./etsin_finder/:/etsin_finder/

configs:
  etsin-qvain-app-config:
    external: True
  etsin-qvain-nginx-config:
    external: True
  fairdata-nginx-config:
    external: True
  fairdata-ssl-certificate:
    external: True
  fairdata-ssl-certificate-key:
    external: True

