[tool.poetry]
name = "fairdata-etsin-qvain"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "<2.0"
Flask-Mail = "^0.9.1"
Flask-RESTful = "^0.3.9"
marshmallow = "^3.14.1"
marshmallow-oneofschema = "^3.0.1"
PyJWT = "<2.0"
blinker = "^1.4"
cryptography = "^36.0.1"
gevent = "^21.12.0"
gunicorn = "^20.1.0"
pymemcache = "^3.5.0"
python-dateutil = "^2.8.2"
python3-saml = "^1.12.0"
PyYAML = "^6.0"
requests = "^2.27.1"
ldap3 = "^2.9.1"
tox = "<4.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
flake8-docstrings = "^1.6.0"
ipdb = "^0.13.9"
pytest = "<5.0"
pytest-cov = "<3.0"
pytest-mock = "<3.1"
requests-mock = "^1.9.3"
pydocstyle = "^6.1.1"
tox = "<4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
