const queryData = {
  size: 20,
  from: 0,
  query: {
    bool: {
      must: [
        {
          simple_query_string: {
            analyze_wildcard: true,
            query: 'Helsinki*',
            minimum_should_match: '25%',
            default_operator: 'or',
            fields: [
              'title.*^5',
              'description.*^3',
              'organization_name*^3',
              'keyword^2',
              'creator.name.*',
              'contributor.name.*',
              'publisher.name.*',
              'rights_holder.name.*',
              'curator.name.*',
              'access_rights.license.title.*',
              'access_rights.access_type.pref_label.*',
              'theme.pref_label.*',
              'field_of_science.pref_label.*',
              'infrastructure.pref_label.*',
              'is_output_of.name.*',
              'identifier',
              'preferred_identifier',
              'other_identifier.notation',
              'other_identifier.type.pref_label.*',
              'dataset_version_set',
            ],
          },
        },
      ],
      filter: [],
    },
  },
  sort: [{ date_modified: { order: 'desc' } }, '_score'],
  _source: [
    'access_rights.*',
    'data_catalog.*',
    'description.*',
    'identifier',
    'preservation_state',
    'title.*',
    'preservation_identifier',
    'preservation_dataset_version',
    'preservation_dataset_origin_version',
    'data_catalog_identifier',
  ],
  highlight: { fields: { 'description.*': {}, 'title.*': {} } },
  aggregations: {
    access_type_fi: { terms: { field: 'access_rights.access_type.pref_label.fi.keyword' } },
    access_type_en: { terms: { field: 'access_rights.access_type.pref_label.en.keyword' } },
    organization_name_fi: { terms: { field: 'organization_name_fi.keyword', size: 40 } },
    organization_name_en: { terms: { field: 'organization_name_en.keyword', size: 40 } },
    creator: { terms: { field: 'creator_name.keyword', size: 40 } },
    field_of_science_en: { terms: { field: 'field_of_science.pref_label.en.keyword', size: 40 } },
    field_of_science_fi: { terms: { field: 'field_of_science.pref_label.fi.keyword', size: 40 } },
    all_keywords_en: { terms: { field: 'all_keywords_en', size: 40 } },
    all_keywords_fi: { terms: { field: 'all_keywords_fi', size: 40 } },
    infrastructure_en: { terms: { field: 'infrastructure.pref_label.en.keyword' } },
    infrastructure_fi: { terms: { field: 'infrastructure.pref_label.fi.keyword' } },
    project_name_fi: { terms: { field: 'project_name_fi.keyword', size: 40 } },
    project_name_en: { terms: { field: 'project_name_en.keyword', size: 40 } },
    file_type_en: { terms: { field: 'file_type.pref_label.en.keyword' } },
    file_type_fi: { terms: { field: 'file_type.pref_label.fi.keyword' } },
    data_catalog_fi: { terms: { field: 'data_catalog.fi' } },
    data_catalog_en: { terms: { field: 'data_catalog.en' } },
  },
}

export default queryData
