// Mock Metax responses
export const metaxResponses = {
  '/es/reference_data/field_of_science/_search': {
    hits: {
      hits: [
        {
          _index: 'reference_data',
          _type: 'field_of_science',
          _id: 'field_of_science_ta1',
          _score: 1.0,
          _source: {
            id: 'field_of_science_ta1',
            code: 'ta1',
            type: 'field_of_science',
            uri: 'http://www.yso.fi/onto/okm-tieteenala/ta1',
            wkt: '',
            input_file_format: '',
            output_format_version: '',
            label: {
              sv: 'Naturvetenskaper',
              en: 'Natural sciences',
              fi: 'LUONNONTIETEET',
              und: 'LUONNONTIETEET',
            },
            parent_ids: [],
            child_ids: [],
            has_children: false,
            same_as: [],
            internal_code: '',
            scheme: 'http://www.yso.fi/onto/okm-tieteenala/conceptscheme',
          },
        },
      ],
    },
  },
  '/es/reference_data/license/_search': {
    hits: {
      hits: [
        {
          _index: 'reference_data',
          _type: 'license',
          _id: 'license_CC0-1.0',
          _score: 1.0,
          _source: {
            id: 'license_CC0-1.0',
            code: 'CC0-1.0',
            type: 'license',
            uri: 'http://uri.suomi.fi/codelist/fairdata/license/code/CC0-1.0',
            wkt: '',
            input_file_format: '',
            output_format_version: '',
            label: {
              fi: 'Creative Commons Yleismaailmallinen (CC0 1.0) Public Domain -lausuma',
              en: 'Creative Commons CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',
              und: 'Creative Commons Yleismaailmallinen (CC0 1.0) Public Domain -lausuma',
            },
            parent_ids: [],
            child_ids: [],
            has_children: false,
            same_as: ['https://creativecommons.org/publicdomain/zero/1.0/'],
            internal_code: '',
            scheme: 'http://uri.suomi.fi/codelist/fairdata/license',
          },
        },
      ],
    },
  },
  '/es/reference_data/access_type/_search': {
    hits: {
      total: 5,
      max_score: 1.0,
      hits: [
        {
          _index: 'reference_data',
          _type: 'access_type',
          _id: 'access_type_embargo',
          _score: 1.0,
          _source: {
            id: 'access_type_embargo',
            code: 'embargo',
            type: 'access_type',
            uri: 'http://uri.suomi.fi/codelist/fairdata/access_type/code/embargo',
            wkt: '',
            input_file_format: '',
            output_format_version: '',
            label: {
              fi: 'Embargo',
              en: 'Embargo',
              und: 'Embargo',
            },
            parent_ids: [],
            child_ids: [],
            has_children: false,
            same_as: ['http://publications.europa.eu/resource/authority/access-right/NON_PUBLIC'],
            internal_code: '',
            scheme: 'http://uri.suomi.fi/codelist/fairdata/access_type',
          },
        },
      ],
    },
  },
  '/es/reference_data/restriction_grounds/_search': {
    took: 0,
    timed_out: false,
    _shards: {
      total: 2,
      successful: 2,
      skipped: 0,
      failed: 0,
    },
    hits: {
      total: 11,
      max_score: 1.0,
      hits: [
        {
          _index: 'reference_data',
          _type: 'restriction_grounds',
          _id: 'restriction_grounds_personal_interest',
          _score: 1.0,
          _source: {
            id: 'restriction_grounds_personal_interest',
            code: 'personal_interest',
            type: 'restriction_grounds',
            uri: 'http://uri.suomi.fi/codelist/fairdata/restriction_grounds/code/personal_interest',
            wkt: '',
            input_file_format: '',
            output_format_version: '',
            label: {
              fi: 'Saatavuutta rajoitettu tietoja antaneen henkilön etuun tai suojaan perustuen tai esim. luovutussopimuksen perusteella',
              en:
                'Restricted access based on the interest or protection of the person who ' +
                'provided the information or, for example, on the basis of extradite',
              sv: 'Begränsad åtkomst på grund av skydd av person',
              und: 'Saatavuutta rajoitettu tietoja antaneen henkilön etuun tai suojaan perustuen tai esim. luovutussopimuksen perusteella',
            },
            parent_ids: [],
            child_ids: [],
            has_children: false,
            same_as: [],
            internal_code: '',
            scheme: 'http://uri.suomi.fi/codelist/fairdata/restriction_grounds',
          },
        },
      ],
    },
  },
  '/es/organization_data/organization/_search': {
    took: 0,
    timed_out: false,
    _shards: {
      total: 2,
      successful: 2,
      skipped: 0,
      failed: 0,
    },
    hits: {
      total: 2439,
      max_score: 1.0,
      hits: [
        {
          _index: 'organization_data',
          _type: 'organization',
          _id: 'organization_10076',
          _score: 1.0,
          _source: {
            id: 'organization_10076',
            code: '10076',
            type: 'organization',
            uri: 'http://uri.suomi.fi/codelist/fairdata/organization/code/10076',
            org_csc: '2',
            parent_id: '',
            label: {
              fi: 'Aalto yliopisto',
              und: 'Aalto yliopisto',
              en: 'Aalto University',
              sv: 'Aalto universitetet',
            },
            same_as: ['http://isni.org/isni/0000000108389418'],
            scheme: 'http://uri.suomi.fi/codelist/fairdata/organization',
          },
        },
      ],
    },
  },
  '/es/reference_data/file_type/_search': {
    took: 0,
    timed_out: false,
    _shards: {
      total: 2,
      successful: 2,
      skipped: 0,
      failed: 0,
    },
    hits: {
      total: 9,
      max_score: 1.0,
      hits: [
        {
          _index: 'reference_data',
          _type: 'file_type',
          _id: 'file_type_video',
          _score: 1.0,
          _source: {
            id: 'file_type_video',
            code: 'video',
            type: 'file_type',
            uri: 'http://uri.suomi.fi/codelist/fairdata/file_type/code/video',
            wkt: '',
            input_file_format: '',
            output_format_version: '',
            label: {
              fi: 'Video',
              en: 'Video',
              und: 'Video',
            },
            parent_ids: [],
            child_ids: [],
            has_children: false,
            same_as: [],
            internal_code: '',
            scheme: 'http://uri.suomi.fi/codelist/fairdata/file_type',
          },
        },
      ],
    },
  },
  '/es/reference_data/use_category/_search': {
    took: 0,
    timed_out: false,
    _shards: {
      total: 2,
      successful: 2,
      skipped: 0,
      failed: 0,
    },
    hits: {
      total: 7,
      max_score: 1.0,
      hits: [
        {
          _index: 'reference_data',
          _type: 'use_category',
          _id: 'use_category_source',
          _score: 1.0,
          _source: {
            id: 'use_category_source',
            code: 'source',
            type: 'use_category',
            uri: 'http://uri.suomi.fi/codelist/fairdata/use_category/code/source',
            wkt: '',
            input_file_format: '',
            output_format_version: '',
            label: {
              fi: 'Lähdeaineisto',
              en: 'Source material',
              und: 'Lähdeaineisto',
            },
            parent_ids: [],
            child_ids: [],
            has_children: false,
            same_as: [],
            internal_code: '',
            scheme: 'http://uri.suomi.fi/codelist/fairdata/use_category',
          },
        },
      ],
    },
  },
}
